//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;

using System.Text;
using TriageClient;


namespace OpenAuth.Repository.Domain
{
    /// <summary>
    /// 
    /// </summary>

    public partial class OUTP_JZJLK : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
        public string GHXH { get; set; }
        private string patientState ;
        public string PatientState
        {
            get
            {
                return patientState;
            }
            set
            {
                patientState = value;
                OnPropertyChanged("PatientState");
            }
        }
        public OUTP_JZJLK()
        {
      
        }

      
        /// <summary>
        /// 
        /// </summary>
        [Description("")]
        public string PATID { get; set; }
        public string HZXM { get; set; }
        public string GHLB { get; set; }
        
    }
}